<a href="https://colab.research.google.com/github/bbcx-investments/notebooks/blob/main/factor_investing/quintiles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from pandas_datareader import DataReader as pdr

# associate names of French files with characteristic names
files = {'Earnings to price ratio': 'Portfolios_Formed_on_E-P',\
 'Variance': 'Portfolios_Formed_on_VAR',\
 'Accruals': 'Portfolios_Formed_on_AC',\
 'Residual variance': 'Portfolios_Formed_on_RESVAR',\
 'Net equity issuance': 'Portfolios_Formed_on_NI',\
 'Beta': 'Portfolios_Formed_on_BETA',\
 'Cash flow to price': 'Portfolios_Formed_on_CF-P',\
 'Market equity': 'Portfolios_Formed_on_ME',\
 'Book to market ratio': 'Portfolios_Formed_on_BE-ME',\
 'Dividend to price ratio': 'Portfolios_Formed_on_D-P',\
 'Investment rate': 'Portfolios_Formed_on_INV',\
 'Momentum': '10_Portfolios_Prior_12_2',\
 'Short term reversal': '10_Portfolios_Prior_1_0',\
 'Long term reversal': '10_Portfolios_Prior_60_13'}

# sort characteristics in alphabetical order
keys = np.sort(list(files.keys()))

# example characteristic
key = 'Accruals'

# read value-weighted monthly returns in decimal format
f = files[key]
d = pdr(f,'famafrench',start=1920)[2]/100

# for momentum and reversal files, combine deciles to form quintiles
if 'Portfolios_Formed_on' not in f :
    cols = d.columns.to_list()
    d['Lo 20'] = d[cols[:2]].mean(axis=1)
    d['Qnt 2'] = d[cols[2:4]].mean(axis=1)
    d['Qnt 3'] = d[cols[4:6]].mean(axis=1)
    d['Qnt 4'] = d[cols[6:8]].mean(axis=1)
    d['Hi 20'] = d[cols[8:]].mean(axis=1)

# for other files, extract quintiles
else :    
    quintiles = ['Lo 20','Qnt 2','Qnt 3','Qnt 4','Hi 20']
    d = d[quintiles].copy()

In [ ]:
d

       Lo 20   Qnt 2   Qnt 3   Qnt 4   Hi 20
Date
1964  0.2285  0.1374  0.1483  0.1700  0.1989
1965  0.2807  0.1186  0.1170  0.1857  0.2113
1966 -0.0040 -0.0537 -0.1201 -0.1110 -0.1681
1967  0.3431  0.2168  0.3330  0.3887  0.3859
1968  0.2684  0.0916  0.1686  0.0864  0.0486
1969 -0.1183 -0.0689 -0.0984 -0.0728 -0.1712
1970 -0.0786  0.0677  0.0801 -0.0621 -0.1317
1971  0.2134  0.0992  0.2489  0.1659  0.2519
1972  0.0779  0.1171  0.2613  0.2065  0.1472
1973 -0.1976 -0.1465 -0.1598 -0.1507 -0.3494
1974 -0.2121 -0.2548 -0.2540 -0.3627 -0.3064
1975  0.4214  0.3715  0.3921  0.4350  0.5764
1976  0.3086  0.2996  0.2295  0.2528  0.2262
1977 -0.0016 -0.0162 -0.0150 -0.0731 -0.0817
1978  0.1311  0.0725  0.0552  0.0675  0.0950
1979  0.3640  0.1529  0.2210  0.1978  0.3199
1980  0.4713  0.3047  0.2623  0.2564  0.5102
1981 -0.1040  0.0325 -0.0438  0.0110 -0.1511
1982  0.2660  0.1819  0.2585  0.2175  0.1537
1983  0.2756  0.2504  0.2324  0.1990  0.2471
1984 -0.0247  0.0568  0.0792  0.0746 -0.0331
1985  0.2415  0.2794  0.3343  0.3471  0.3288
1986  0.1378  0.2400  0.2789  0.1404  0.0145
1987  0.1110  0.0383  0.0449  0.0416  0.0027
1988  0.2110  0.1894  0.1601  0.1369  0.2199
1989  0.2899  0.3585  0.3605  0.2042  0.1934
1990 -0.0236 -0.0068 -0.0185 -0.0208 -0.1195
1991  0.3637  0.2421  0.2677  0.4084  0.4428
1992  0.0848  0.0270  0.0610  0.0811  0.1004
1993  0.1671  0.1059  0.1373  0.0524  0.0206
1994  0.0265  0.0626 -0.0045  0.0111 -0.0158
1995  0.3648  0.3897  0.3240  0.3193  0.2642
1996  0.1406  0.2045  0.1720  0.2783  0.1068
1997  0.2419  0.3065  0.2663  0.2907  0.1561
1998  0.3814  0.2343  0.2403  0.3563  0.1491
1999  0.4249  0.2361  0.1846  0.2327  0.2478
2000 -0.2112 -0.1457 -0.0890 -0.0114 -0.1466
2001 -0.1221 -0.1152 -0.1054 -0.1850 -0.1252
2002 -0.2205 -0.2354 -0.2031 -0.1802 -0.3090
2003  0.3470  0.2906  0.2317  0.3713  0.3181
2004  0.1258  0.1242  0.0742  0.1330  0.1499
2005  0.0872  0.0304  0.0865  0.0442  0.1233
2006  0.1486  0.1537  0.1251  0.1426  0.1917
2007  0.2075  0.1007  0.1282  0.0947  0.0714
2008 -0.4702 -0.3368 -0.2981 -0.3155 -0.2813
2009  0.4551  0.2675  0.2489  0.3694  0.3624
2010  0.2415  0.1974  0.1280  0.1678  0.2141
2011  0.0815  0.1183  0.0455  0.0372 -0.0542
2012  0.1384  0.1366  0.1634  0.1558  0.1285
2013  0.2643  0.3678  0.3327  0.3262  0.4053
2014  0.0766  0.1731  0.1029  0.1291  0.1078
2015  0.0942  0.0537 -0.0321 -0.0577 -0.0637
2016  0.0805  0.0850  0.1527  0.1585  0.1254
2017  0.2746  0.2791  0.2180  0.2125  0.2083
2018  0.0767 -0.0072 -0.1107 -0.0126 -0.1030
2019  0.3987  0.2827  0.2745  0.2240  0.3209
2020  0.2817  0.2315  0.2396  0.2782  0.4099
2021  0.2603  0.3329  0.2342  0.1126  0.1872

In [ ]:
(1+d).cumprod()

            Lo 20       Qnt 2       Qnt 3       Qnt 4       Hi 20
Date
1964     1.228500    1.137400    1.148300    1.170000    1.198900
1965     1.573340    1.272296    1.282651    1.387269    1.452228
1966     1.567047    1.203973    1.128605    1.233282    1.208108
1967     2.104700    1.464995    1.504430    1.712659    1.674317
1968     2.669602    1.599188    1.758077    1.860633    1.755689
1969     2.353788    1.489004    1.585082    1.725179    1.455115
1970     2.168780    1.589810    1.712047    1.618045    1.263476
1971     2.631598    1.747519    2.138176    1.886479    1.581746
1972     2.836599    1.952153    2.696881    2.276036    1.814579
1973     2.276087    1.666163    2.265920    1.933038    1.180565
1974     1.793329    1.241625    1.690376    1.231925    0.818840
1975     2.549038    1.702888    2.353172    1.767812    1.290819
1976     3.335671    2.213073    2.893226    2.214715    1.582803
1977     3.330334    2.177222    2.849827    2.052820    1.453488
1978     3.766941    2.335070    3.007138    2.191385    1.591569
1979     5.138108    2.692103    3.671715    2.624841    2.100712
1980     7.559698    3.512386    4.634806    3.297850    3.172495
1981     6.773489    3.626539    4.431801    3.334126    2.693131
1982     8.575237    4.286206    5.577422    4.059299    3.107065
1983    10.938573    5.359472    6.873615    4.867099    3.874821
1984    10.668390    5.663890    7.418005    5.230185    3.746565
1985    13.244806    7.246381    9.897844    7.045582    4.978435
1986    15.069940    8.985512   12.658353    8.034782    5.050622
1987    16.742704    9.329658   13.226713    8.369029    5.064259
1988    20.275414   11.096695   15.344310    9.514749    6.177889
1989    26.153257   15.074860   20.875934   11.457661    7.372693
1990    25.536040   14.972351   20.489729   11.219342    6.491656
1991    34.823498   18.597157   25.974829   15.801321    9.366162
1992    37.776530   19.099280   27.559294   17.082808   10.306525
1993    44.088988   21.121894   31.343185   17.977947   10.518839
1994    45.257347   22.444124   31.202141   18.177502   10.352641
1995    61.767227   31.190600   41.311634   23.981578   13.087809
1996    70.451699   37.569077   48.417235   30.655652   14.485587
1997    87.493965   49.083999   61.310745   39.567250   16.746787
1998   120.864163   60.584380   76.043717   53.665061   19.243733
1999   172.219346   74.888353   90.081387   66.152920   24.012330
2000   135.846620   63.977120   82.064144   65.398777   20.492123
2001   119.259748   56.606955   73.414583   53.300003   17.926509
2002    92.962973   43.281678   58.504081   43.695343   12.387218
2003   125.221125   55.859334   72.059477   59.919423   16.327592
2004   140.973943   62.797063   77.406290   67.888707   18.775098
2005   153.266870   64.706094   84.101934   70.889388   21.090067
2006   176.042327   74.651420   94.623086   80.998214   25.133033
2007   212.571110   82.168818  106.753766   88.668745   26.927532
2008   112.620174   54.494360   74.930468   60.693756   19.352817
2009   163.873615   69.071602   93.580662   83.114030   26.366278
2010   203.449094   82.706336  105.558986   97.060564   32.011298
2011   220.030195   92.490496  110.361920  100.671217   30.276286
2012   250.482374  105.124697  128.395058  116.355792   34.166788
2013   316.684865  143.789561  171.112094  154.311052   48.014588
2014   340.942926  168.679534  188.719528  174.232608   53.190560
2015   373.059749  177.737625  182.661632  164.179387   49.802322
2016   403.091059  192.845323  210.554063  190.201820   56.047533
2017   513.779864  246.668453  256.454848  230.619706   67.722234
2018   553.186780  244.892440  228.065297  227.713898   60.746844
2019   773.742349  314.123532  290.669221  278.721811   80.240506
2020   991.705568  386.843130  360.313566  356.262219  113.131089
2021  1249.846528  515.623208  444.699003  396.377345  134.309229